#!/bin/sh

branch="$(git branch --show-current)"

if [[ ! "$branch" =~ ^(main|dev|(feat|fix|chore)/.+)$ ]]; then
  echo "❌ invalid branch name: $branch"
  echo "허용 브랜치:"
  echo "- main"
  echo "- dev"
  echo "- feat/*, fix/*, chore/*"
  exit 1
fi
